Fix #1 and test returning exit code

diff --git a/bin/run b/bin/run
--- a/bin/run
+++ b/bin/run
@@ -19,6 +19,7 @@ cp -r /ssh/. /root/.ssh
 
 # Run buildpack
 /bin/build
+RETURN_VALUE="$?"
 
 # Normalize stderr paths (remove all parent dirs)
 find-and-replace-in "$WORKSPACE_DIR/" "" $STDERR_LOG
@@ -27,3 +28,6 @@ TIME_END=`date +%s.%N`
 RUNTIME=`echo "$TIME_END $TIME_START" | awk '{print $1-$2}'`
 echo "Finished in: $RUNTIME seconds"
 echo $RUNTIME > $ELAPSED_LOG
+
+# Exit with buildpack's return value
+exit $RETURN_VALUE
